-- 1. DATABASE CREATION
CREATE DATABASE OnlineMarketplace;
USE OnlineMarketplace;

-- Create the `Products` table
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Category VARCHAR(50),
    Description TEXT
);

-- Create the `Vendors` table
CREATE TABLE Vendors (
    VendorID INT AUTO_INCREMENT PRIMARY KEY,
    VendorName VARCHAR(100) NOT NULL,
    CommissionRate DECIMAL(5, 2) NOT NULL
);

-- Create the `Customers` table
CREATE TABLE Customers (
    ShopperID INT PRIMARY KEY,
    ShopperName VARCHAR(100),
    Email VARCHAR(100) UNIQUE,
    IsMember BOOLEAN,
    SignupDate DATE
);

-- Create the `Orders` table
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    ShopperID INT,
    OrderDate DATE,
    Status ENUM('Complete', 'Pending', 'Cancelled'),
    TotalAmount DECIMAL(10, 2),
    FOREIGN KEY (ShopperID) REFERENCES Customers(ShopperID)
);

-- Create the `OrderDetails` table (to handle multiple products per order)
CREATE TABLE OrderDetails (
    OrderDetailID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT,
    ProductID INT,
    Quantity INT,
    Price DECIMAL(10, 2),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

-- Create the `Reviews` table
CREATE TABLE Reviews (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT,
    CustomerID INT,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    ReviewText TEXT,
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (CustomerID) REFERENCES Customers(ShopperID)
);

-- Create a trigger to validate reviews (example)
DELIMITER $$
CREATE TRIGGER ValidateRating
BEFORE INSERT ON Reviews
FOR EACH ROW
BEGIN
    IF NEW.Rating < 1 OR NEW.Rating > 5 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Invalid rating value';
    END IF;
END $$
DELIMITER ;
ALTER TABLE Customers DROP INDEX Email;

-- Load data into Customers table
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/customers.csv'
INTO TABLE Customers
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ShopperID, ShopperName, Email, IsMember, @SignupDate)
SET SignupDate = STR_TO_DATE(@SignupDate, '%d-%m-%Y');

INSERT INTO Customers (ShopperID, ShopperName, Email, IsMember, SignupDate)
SELECT DISTINCT ShopperID, 'Unknown', 'unknown@example.com', 0, CURDATE()
FROM Orders
WHERE ShopperID NOT IN (SELECT ShopperID FROM Customers);

-- Load data into Orders table
SET FOREIGN_KEY_CHECKS = 0;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/orders.csv'
INTO TABLE Orders
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(OrderID, ShopperID, OrderDate, @Status, TotalAmount)
SET OrderDate = STR_TO_DATE(OrderDate, '%Y-%m-%d'),
    Status = CASE
                WHEN @Status IN ('Complete', 'Pending', 'Cancelled') THEN @Status
                ELSE 'Pending'
             END;
SET FOREIGN_KEY_CHECKS = 1;


-- Load data into Products table
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/products.csv'
INTO TABLE Products
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ProductID, ProductName, Category, Description);

-- Load data into OrderDetails table
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/order_details.csv'
INTO TABLE OrderDetails
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(OrderDetailID, OrderID, ProductID, Quantity, Price);

ALTER TABLE Reviews DROP FOREIGN KEY reviews_ibfk_2;
-- Load data into Reviews table
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/reviews.csv'
INTO TABLE Reviews
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ReviewID, ProductID, CustomerID, Rating, ReviewText);

-- Task 2: SQL Queries Addressing Objectives

-- Objective 1: Retrieve all orders with customer names, total amounts, and order statuses
SELECT o.OrderID, c.ShopperName, o.Status, o.TotalAmount
FROM Orders o
JOIN Customers c ON o.ShopperID = c.ShopperID;

-- Objective 2: Calculate total revenue generated by each customer
SELECT c.ShopperID, c.ShopperName, SUM(o.TotalAmount) AS TotalRevenue
FROM Customers c
LEFT JOIN Orders o ON c.ShopperID = o.ShopperID
GROUP BY c.ShopperID, c.ShopperName
ORDER BY TotalRevenue DESC;

-- Objective 3: Identify products with no associated orders
SELECT p.ProductID, p.ProductName
FROM Products p
LEFT JOIN OrderDetails od ON p.ProductID = od.ProductID
WHERE od.ProductID IS NULL;

-- Demonstrating Specific SQL Techniques

-- JOIN Operations: Retrieve all completed orders with product details
SELECT o.OrderID, p.ProductName, od.Quantity, o.TotalAmount
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
WHERE o.Status = 'Complete';

-- Filtering: Retrieve all orders placed in the year 2023
SELECT *
FROM Orders
WHERE YEAR(OrderDate) = 2023;

-- Aggregation: Calculate the average order value for completed orders
SELECT AVG(TotalAmount) AS AverageOrderValue
FROM Orders
WHERE Status = 'Complete';

-- Operation with Strings: Find customers with Gmail accounts
SELECT ShopperID, ShopperName, Email
FROM Customers
WHERE Email LIKE '%@gmail.com';

-- Set Operations: Retrieve products ordered in 2023 but not in 2022
SELECT DISTINCT p.ProductID, p.ProductName
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
JOIN Orders o ON od.OrderID = o.OrderID
WHERE YEAR(o.OrderDate) = 2023
EXCEPT
SELECT DISTINCT p.ProductID, p.ProductName
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
JOIN Orders o ON od.OrderID = o.OrderID
WHERE YEAR(o.OrderDate) = 2022;

-- Window Function: Rank customers by their total spending
SELECT c.ShopperID, c.ShopperName, SUM(o.TotalAmount) AS TotalSpending,
       RANK() OVER (ORDER BY SUM(o.TotalAmount) DESC) AS `Rank`
FROM Customers c
LEFT JOIN Orders o ON c.ShopperID = o.ShopperID
GROUP BY c.ShopperID, c.ShopperName;


-- Stored Procedure for Monthly Report
DELIMITER $$
CREATE PROCEDURE monthly_report(IN report_month VARCHAR(7))
BEGIN
    SELECT DATE_FORMAT(OrderDate, '%Y-%m') AS OrderMonth,
           SUM(TotalAmount) AS TotalRevenue,
           SUM(TotalAmount * 0.1) AS MarketplaceProfit, -- Assuming 10% commission rate
           COUNT(OrderID) AS TotalOrders
    FROM Orders
    WHERE DATE_FORMAT(OrderDate, '%Y-%m') = report_month
    GROUP BY OrderMonth;
END $$
DELIMITER ;

-- Example: Call the procedure for January 2023
CALL monthly_report('2023-01');